### PR TITLE
feat: Update files with qualification if not present

### PR DESCRIPTION
**Pull request by KillianCourvoisier**
This PR is made to ensure files are replaced if a qualification has been added to it since last execution

### CODE REVIEW

**Comment by KillianCourvoisier** [comment]
@Crash-- Je ne comprends pas l'erreur de build, il semblerait que la cause soit prettier mais tout est bien indenté, je n'ai rien touché d'autres que le test ajouté, qu'est-ce qui ne lui va pas ? 🤔

**Comment by doubleface** [comment]
@KillianCourvoisier Please fix lint errors

**Comment by KillianCourvoisier** [comment]
@doubleface that's what im asking Crash in the first comment

I don't know where it comes from, I just added the test and touch nothing else

**Comment by Crash--** [comment]
@KillianCourvoisier run `yarn lint` you should have an error. Then run `yarn lint --fix` and you should have the fix. 


```
diff --git a/packages/cozy-konnector-libs/src/libs/saveFiles.spec.js b/packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
index c336d7a..e64f2f6 100644
--- a/packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
+++ b/packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
@@ -378,7 +378,7 @@ describe('saveFiles', function () {
                 name: 'bill.pdf',
                 metadata: {
                   carbonCopy: true,
-                  qualification : {
+                  qualification: {
                     item1: true,
                     item2: 'toto'
                   }
```

**Review by Crash-- — APPROVED** [review]

**Pull request merged**
