### PR TITLE
Feat/download file in worker

### PR DESCRIPTION
**Pull request by LucsT**
This PR implement the fonction that will call by launcher to download file in worker.

We remove the download during saveFiles and the filtering logic.
Filtering logic launcher side, will be implemented in the next step.

Will be used in app by https://github.com/cozy/cozy-flagship-app/pull/633

### CODE REVIEW

**Comment by Crash--** [comment]
Please give us some context on this PR. Why did you do this change?

**Comment by LucsT** [comment]
I have do this change in this card context  : https://trello.com/c/ZSEywYCe/229-%F0%9F%93%A5-perf-t%C3%A9l%C3%A9charger-les-fichiers-au-fur-et-%C3%A0-mesure

The final goal is to be able to let the launcher decided which file we need to download (Website  -> App) to reduce the number of file to download each time we execute the connector.

The first step is to be able to download the file in worker. 
This is the feature added by this PR and https://github.com/cozy/cozy-flagship-app/pull/633
Exactly, this PR bring to the contentScript (so the konnector) the ability to download with this function.


The second step will based on this and will add the filtering based on filename and metadata in the saveFiles of the flagship app.

Do you need more context or details ?

**Comment by LucsT** [comment]
Not a draft anymore, I 'publish' the PR.

**Comment by doubleface** [comment]
@LucsT Please add this context in the main commit and it will be ok for me

**Comment by LucsT** [comment]
Enhance commit body

**Review by doubleface — APPROVED** [review]

**Pull request merged**
